<?php if ($isLocked && $aiSummary !== null): ?>
<section class="surface-primary mt-4">
    <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
            <h2 class="text-lg font-semibold text-slate-50">AI Briefing</h2>
            <?php $verdict = (string) ($aiSummary['verdict'] ?? ''); ?>
            <?php if ($verdict !== ''): ?>
                <span class="inline-block rounded-full px-2.5 py-0.5 text-xs font-semibold uppercase tracking-wider <?= theater_ai_verdict_color_class($verdict) ?> <?= str_contains($verdict, 'victory') ? 'bg-green-900/40' : (str_contains($verdict, 'defeat') ? 'bg-red-900/40' : 'bg-slate-700') ?>">
                    <?= htmlspecialchars(theater_ai_verdict_label($verdict), ENT_QUOTES) ?>
                </span>
            <?php endif; ?>
            <?php if ($justLocked): ?>
                <span class="text-[10px] text-green-400 uppercase tracking-wider">Locked</span>
            <?php endif; ?>
        </div>
        <span class="inline-flex items-center gap-1.5 rounded-full bg-slate-700 px-2.5 py-1 text-[10px] uppercase tracking-wider text-slate-300">
            <svg class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
            Locked
        </span>
    </div>
    <p class="mt-2 text-base font-medium text-slate-100"><?= htmlspecialchars((string) ($aiSummary['headline'] ?? ''), ENT_QUOTES) ?></p>
    <div class="mt-3 prose prose-invert prose-sm max-w-none text-slate-300 leading-relaxed
                prose-headings:text-slate-100 prose-headings:font-semibold prose-headings:mt-4 prose-headings:mb-2
                prose-strong:text-slate-100 prose-li:text-slate-300 prose-ul:my-1 prose-ol:my-1">
        <?php
            $rawSummary = (string) ($aiSummary['summary'] ?? '');
            $rendered = htmlspecialchars($rawSummary, ENT_QUOTES);
            // Bold and italic
            $rendered = preg_replace('/\*\*(.+?)\*\*/', '<strong>$1</strong>', $rendered);
            $rendered = preg_replace('/\*(.+?)\*/', '<em>$1</em>', $rendered);
            // Markdown headers: ## Header and ### Header
            $rendered = preg_replace('/^###\s+(.+)$/m', '<h4>$1</h4>', $rendered);
            $rendered = preg_replace('/^##\s+(.+)$/m', '<h3>$1</h3>', $rendered);
            // Numbered section headers: 1. **Title**
            $rendered = preg_replace('/^(\d+)\.\s*<strong>(.+?)<\/strong>/m', '<h3>$1. $2</h3>', $rendered);
            // Bullet lists
            $rendered = preg_replace_callback('/(?:^- .+$\n?)+/m', static function (array $m): string {
                $items = preg_split('/\n/', trim($m[0]));
                $lis = '';
                foreach ($items as $item) {
                    $text = preg_replace('/^- /', '', $item);
                    if ($text !== '') $lis .= '<li>' . $text . '</li>';
                }
                return '<ul>' . $lis . '</ul>';
            }, $rendered);
            // Numbered lists (1. item, 2. item)
            $rendered = preg_replace_callback('/(?:^\d+\.\s+.+$\n?)+/m', static function (array $m): string {
                $items = preg_split('/\n/', trim($m[0]));
                $lis = '';
                foreach ($items as $item) {
                    $text = preg_replace('/^\d+\.\s+/', '', $item);
                    if ($text !== '') $lis .= '<li>' . $text . '</li>';
                }
                return '<ol>' . $lis . '</ol>';
            }, $rendered);
            // Paragraphs
            $rendered = preg_replace('/\n{2,}/', '</p><p>', $rendered);
            $rendered = str_replace("\n", '<br>', $rendered);
            echo '<p>' . $rendered . '</p>';
        ?>
    </div>
    <p class="mt-3 text-[10px] text-slate-500">Generated by <?= htmlspecialchars((string) ($aiSummary['model'] ?? ''), ENT_QUOTES) ?> at <?= htmlspecialchars((string) ($aiSummary['generated_at'] ?? ''), ENT_QUOTES) ?> · Locked <?= htmlspecialchars((string) ($theater['locked_at'] ?? ''), ENT_QUOTES) ?></p>
</section>
<?php elseif ($isLocked): ?>
<section class="surface-primary mt-4">
    <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
            <h2 class="text-lg font-semibold text-slate-50">AI Briefing</h2>
        </div>
        <span class="inline-flex items-center gap-1.5 rounded-full bg-slate-700 px-2.5 py-1 text-[10px] uppercase tracking-wider text-slate-300">
            <svg class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
            Locked
        </span>
    </div>
    <?php if ($aarError !== null): ?>
        <p class="text-sm text-red-400 mt-2">AI generation failed at lock time: <?= htmlspecialchars($aarError, ENT_QUOTES) ?></p>
    <?php else: ?>
        <p class="text-sm text-muted mt-2">Report locked but no AI briefing was generated (AI may be disabled).</p>
    <?php endif; ?>
    <p class="mt-2 text-[10px] text-slate-500">Locked <?= htmlspecialchars((string) ($theater['locked_at'] ?? ''), ENT_QUOTES) ?></p>
</section>
<?php elseif (!$isLocked): ?>
<section class="surface-primary mt-4">
    <div class="flex items-center justify-between">
        <div>
            <h2 class="text-lg font-semibold text-slate-50">AI Briefing</h2>
            <p class="text-sm text-muted mt-1">Lock this battle report to generate a one-time AI briefing. Once locked, the report cannot be regenerated.</p>
        </div>
        <button type="button" id="lock-theater-btn"
                class="inline-flex items-center gap-2 rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-amber-500 transition-colors"
                onclick="theaterLockStart('<?= htmlspecialchars($theaterId, ENT_QUOTES) ?>')">
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
            Lock &amp; Generate AI Report
        </button>
    </div>
</section>

<!-- Lock processing overlay -->
<div id="lock-overlay" class="fixed inset-0 z-50 hidden">
    <div class="absolute inset-0 bg-black/90 backdrop-blur-sm"></div>
    <div class="relative flex flex-col items-center justify-center h-full px-6">
        <!-- Spinner -->
        <div class="relative mb-8">
            <div class="w-20 h-20 rounded-full border-2 border-amber-500/20"></div>
            <div class="absolute inset-0 w-20 h-20 rounded-full border-2 border-transparent border-t-amber-500 animate-spin"></div>
            <div class="absolute inset-2 w-16 h-16 rounded-full border-2 border-transparent border-b-blue-500/70 animate-spin" style="animation-duration: 1.5s; animation-direction: reverse;"></div>
            <svg class="absolute inset-0 m-auto h-8 w-8 text-amber-500/80" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
        </div>

        <h2 class="text-xl font-semibold text-slate-100 mb-2">Generating Battle Report</h2>
        <p class="text-sm text-slate-400 mb-1" id="lock-status-text">Materializing theater data...</p>
        <p class="text-xs text-slate-600 mb-10" id="lock-elapsed">0s</p>

        <!-- Lore quote -->
        <div class="max-w-lg text-center">
            <p class="text-sm text-slate-300/80 italic leading-relaxed" id="lock-lore-text"></p>
            <p class="text-[10px] text-slate-500 mt-2" id="lock-lore-source"></p>
        </div>
    </div>
</div>

<script>
(() => {
    const LORE = [
        { text: "In the beginning there was the Void, and the Void was without form, and darkness was upon it.", source: "The Book of Emptiness, Amarr Scriptures" },
        { text: "Among all the stargates that litter the New Eden cluster, there are a few that serve as chokepoints, controlling access to entire regions of space.", source: "Interstellar Navigation Primer" },
        { text: "The capsuleer does not fear death. The capsuleer fears irrelevance.", source: "Caldari Naval Academy" },
        { text: "War is not about destroying your enemy. War is about destroying your enemy's will to fight.", source: "Attributed to Jamyl Sarum I" },
        { text: "Every gate camp, every bubble, every lost ship — these are the threads that weave the tapestry of null-sec sovereignty.", source: "Alliance Tournament Commentary" },
        { text: "The Minmatar do not seek freedom because they lack chains. They seek freedom because they remember them.", source: "A History of the Minmatar People" },
        { text: "There is no such thing as an unfair fight. There is only the prepared and the unprepared.", source: "Guristas Tactical Manual" },
        { text: "To fly a Titan is to carry the weight of an empire on your capacitor.", source: "Capital Warfare Doctrine, CONCORD Archives" },
        { text: "You haven't truly lived in null-sec until you've watched a Keepstar die.", source: "Common capsuleer saying" },
        { text: "The overview doesn't lie. But it does sometimes lag.", source: "Fleet Commander proverb" },
        { text: "Space is cold and empty, but local chat is colder and emptier.", source: "Wormhole Survival Guide" },
        { text: "The greatest fleet commander is the one whose pilots log in.", source: "Old coalition wisdom" },
        { text: "Trust, but verify. Then verify again. Then check d-scan.", source: "Pandemic Horde Newbro Manual" },
        { text: "A single cyno can change the course of history.", source: "B-R5RB After Action Report" },
        { text: "In nullsec, your allies are the friends you haven't reset yet.", source: "Diplomatic Relations 101" },
        { text: "Every structure timer is someone's alarm clock.", source: "Sovereignty warfare handbook" },
        { text: "The Jove gazed upon the empires below and saw only children playing with fire.", source: "The Jovian Decline, Chapter VII" },
        { text: "Warp drive active.", source: "Aura" },
        { text: "The capacitor is empty.", source: "Every pilot's last words" },
        { text: "Somewhere in New Eden, right now, a Venture pilot is mining in a war zone, completely unbothered.", source: "r/Eve" },
        { text: "FC, can I bring my Drake?", source: "The eternal question" },
        { text: "Gate is red. Gate is always red.", source: "Scout wisdom" },
        { text: "Your clone is your most valuable asset. Everything else is ammunition.", source: "Society of Conscious Thought" },
    ];

    let pollInterval = null;
    let elapsedInterval = null;
    let startTime = 0;
    let loreIndex = 0;

    function shuffleArray(arr) {
        for (let i = arr.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [arr[i], arr[j]] = [arr[j], arr[i]];
        }
        return arr;
    }

    const shuffledLore = shuffleArray([...LORE]);

    function showLore() {
        const lore = shuffledLore[loreIndex % shuffledLore.length];
        const textEl = document.getElementById('lock-lore-text');
        const sourceEl = document.getElementById('lock-lore-source');
        textEl.style.opacity = '0';
        sourceEl.style.opacity = '0';
        setTimeout(() => {
            textEl.textContent = '"' + lore.text + '"';
            sourceEl.textContent = '— ' + lore.source;
            textEl.style.opacity = '1';
            sourceEl.style.opacity = '1';
        }, 400);
        loreIndex++;
    }

    function updateElapsed() {
        const sec = Math.floor((Date.now() - startTime) / 1000);
        const el = document.getElementById('lock-elapsed');
        if (el) el.textContent = sec + 's';
    }

    function setStatus(text) {
        const el = document.getElementById('lock-status-text');
        if (el) el.textContent = text;
    }

    window.theaterLockStart = function(theaterId) {
        if (!confirm('Lock this battle report and generate the AI briefing? This action cannot be undone.')) {
            return;
        }

        // Show overlay
        const overlay = document.getElementById('lock-overlay');
        overlay.classList.remove('hidden');
        document.body.style.overflow = 'hidden';

        // Add transitions for lore
        const textEl = document.getElementById('lock-lore-text');
        const sourceEl = document.getElementById('lock-lore-source');
        textEl.style.transition = 'opacity 0.4s ease';
        sourceEl.style.transition = 'opacity 0.4s ease';

        startTime = Date.now();
        elapsedInterval = setInterval(updateElapsed, 1000);
        showLore();
        setInterval(showLore, 8000);

        // Disable the button
        const btn = document.getElementById('lock-theater-btn');
        if (btn) btn.disabled = true;

        // Fire the async lock request
        const formData = new FormData();
        formData.append('theater_id', theaterId);

        fetch('/theater-intelligence/lock.php', {
            method: 'POST',
            body: formData,
        }).catch(() => {
            // Connection might close — that's OK, we poll
        });

        // Start polling
        setStatus('Materializing theater data...');
        const statusMessages = [
            { after: 5, text: 'Rebuilding alliance summaries...' },
            { after: 15, text: 'Computing participant statistics...' },
            { after: 30, text: 'Generating AI briefing...' },
            { after: 60, text: 'Still generating — large battle report...' },
            { after: 120, text: 'Almost there — finalizing report...' },
            { after: 180, text: 'This is a big one — hang tight...' },
        ];

        pollInterval = setInterval(() => {
            const elapsed = (Date.now() - startTime) / 1000;

            // Update status message based on elapsed time
            for (let i = statusMessages.length - 1; i >= 0; i--) {
                if (elapsed >= statusMessages[i].after) {
                    setStatus(statusMessages[i].text);
                    break;
                }
            }

            fetch('/theater-intelligence/lock-status.php?theater_id=' + encodeURIComponent(theaterId))
                .then(r => r.json())
                .then(data => {
                    if (data.status === 'complete') {
                        clearInterval(pollInterval);
                        clearInterval(elapsedInterval);
                        setStatus('Report complete! Redirecting...');
                        setTimeout(() => {
                            window.location.href = '/theater-intelligence/view.php?theater_id=' + encodeURIComponent(theaterId);
                        }, 1000);
                    } else if (data.status === 'unlocked') {
                        // Lock was rolled back — error occurred
                        clearInterval(pollInterval);
                        clearInterval(elapsedInterval);
                        overlay.classList.add('hidden');
                        document.body.style.overflow = '';
                        if (btn) btn.disabled = false;
                        alert('Lock failed — please check the server logs and try again.');
                    }
                })
                .catch(() => {
                    // Network error — keep polling
                });
        }, 2000);
    };
})();
</script>
<?php endif; ?>
