<?php if ($aiSummary !== null): ?>
<section class="surface-primary mt-4">
    <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
            <h2 class="text-lg font-semibold text-slate-50">AI Briefing</h2>
            <?php $verdict = (string) ($aiSummary['verdict'] ?? ''); ?>
            <?php if ($verdict !== ''): ?>
                <span class="inline-block rounded-full px-2.5 py-0.5 text-xs font-semibold uppercase tracking-wider <?= theater_ai_verdict_color_class($verdict) ?> <?= str_contains($verdict, 'victory') ? 'bg-green-900/40' : (str_contains($verdict, 'defeat') ? 'bg-red-900/40' : 'bg-slate-700') ?>">
                    <?= htmlspecialchars(theater_ai_verdict_label($verdict), ENT_QUOTES) ?>
                </span>
            <?php endif; ?>
            <?php if ($aarRegenerated): ?>
                <span class="text-[10px] text-green-400 uppercase tracking-wider">Regenerated</span>
            <?php endif; ?>
        </div>
        <form method="POST" class="inline">
            <input type="hidden" name="regenerate_aar" value="1">
            <button type="submit" class="btn-secondary text-xs" onclick="this.disabled=true;this.textContent='Generating…';this.form.submit();">Regenerate AAR</button>
        </form>
    </div>
    <p class="mt-2 text-base font-medium text-slate-100"><?= htmlspecialchars((string) ($aiSummary['headline'] ?? ''), ENT_QUOTES) ?></p>
    <div class="mt-3 prose prose-invert prose-sm max-w-none text-slate-300 leading-relaxed
                prose-headings:text-slate-100 prose-headings:font-semibold prose-headings:mt-4 prose-headings:mb-2
                prose-strong:text-slate-100 prose-li:text-slate-300 prose-ul:my-1 prose-ol:my-1">
        <?php
            $rawSummary = (string) ($aiSummary['summary'] ?? '');
            $rendered = htmlspecialchars($rawSummary, ENT_QUOTES);
            $rendered = preg_replace('/\*\*(.+?)\*\*/', '<strong>$1</strong>', $rendered);
            $rendered = preg_replace('/\*(.+?)\*/', '<em>$1</em>', $rendered);
            $rendered = preg_replace('/^(\d+)\.\s*<strong>(.+?)<\/strong>/m', '<h3>$1. $2</h3>', $rendered);
            $rendered = preg_replace_callback('/(?:^- .+$\n?)+/m', static function (array $m): string {
                $items = preg_split('/\n/', trim($m[0]));
                $lis = '';
                foreach ($items as $item) {
                    $text = preg_replace('/^- /', '', $item);
                    $lis .= '<li>' . $text . '</li>';
                }
                return '<ul>' . $lis . '</ul>';
            }, $rendered);
            $rendered = preg_replace('/\n{2,}/', '</p><p>', $rendered);
            $rendered = str_replace("\n", '<br>', $rendered);
            echo '<p>' . $rendered . '</p>';
        ?>
    </div>
    <p class="mt-3 text-[10px] text-slate-500">Generated by <?= htmlspecialchars((string) ($aiSummary['model'] ?? ''), ENT_QUOTES) ?> at <?= htmlspecialchars((string) ($aiSummary['generated_at'] ?? ''), ENT_QUOTES) ?></p>
</section>
<?php elseif (supplycore_ai_ollama_enabled()): ?>
<section class="surface-primary mt-4">
    <div class="flex items-center justify-between">
        <div>
            <h2 class="text-lg font-semibold text-slate-50">AI Briefing</h2>
            <?php if ($aarError !== null): ?>
                <p class="text-sm text-red-400 mt-1">AAR generation failed: <?= htmlspecialchars($aarError, ENT_QUOTES) ?></p>
            <?php else: ?>
                <p class="text-sm text-muted mt-1">No AAR has been generated for this theater yet.</p>
            <?php endif; ?>
        </div>
        <form method="POST" class="inline">
            <input type="hidden" name="regenerate_aar" value="1">
            <button type="submit" class="btn-secondary text-xs" onclick="this.disabled=true;this.textContent='Generating…';this.form.submit();">Generate AAR</button>
        </form>
    </div>
</section>
<?php endif; ?>
