<?php if ($isLocked && $aiSummary !== null): ?>
<section class="surface-primary mt-4">
    <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
            <h2 class="text-lg font-semibold text-slate-50">AI Briefing</h2>
            <?php $verdict = (string) ($aiSummary['verdict'] ?? ''); ?>
            <?php if ($verdict !== ''): ?>
                <span class="inline-block rounded-full px-2.5 py-0.5 text-xs font-semibold uppercase tracking-wider <?= theater_ai_verdict_color_class($verdict) ?> <?= str_contains($verdict, 'victory') ? 'bg-green-900/40' : (str_contains($verdict, 'defeat') ? 'bg-red-900/40' : 'bg-slate-700') ?>">
                    <?= htmlspecialchars(theater_ai_verdict_label($verdict), ENT_QUOTES) ?>
                </span>
            <?php endif; ?>
            <?php if ($justLocked): ?>
                <span class="text-[10px] text-green-400 uppercase tracking-wider">Locked</span>
            <?php endif; ?>
        </div>
        <span class="inline-flex items-center gap-1.5 rounded-full bg-slate-700 px-2.5 py-1 text-[10px] uppercase tracking-wider text-slate-300">
            <svg class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
            Locked
        </span>
    </div>
    <p class="mt-2 text-base font-medium text-slate-100"><?= htmlspecialchars((string) ($aiSummary['headline'] ?? ''), ENT_QUOTES) ?></p>
    <div class="mt-3 prose prose-invert prose-sm max-w-none text-slate-300 leading-relaxed
                prose-headings:text-slate-100 prose-headings:font-semibold prose-headings:mt-4 prose-headings:mb-2
                prose-strong:text-slate-100 prose-li:text-slate-300 prose-ul:my-1 prose-ol:my-1">
        <?php
            $rawSummary = (string) ($aiSummary['summary'] ?? '');
            $rendered = htmlspecialchars($rawSummary, ENT_QUOTES);
            // Bold and italic
            $rendered = preg_replace('/\*\*(.+?)\*\*/', '<strong>$1</strong>', $rendered);
            $rendered = preg_replace('/\*(.+?)\*/', '<em>$1</em>', $rendered);
            // Markdown headers: ## Header and ### Header
            $rendered = preg_replace('/^###\s+(.+)$/m', '<h4>$1</h4>', $rendered);
            $rendered = preg_replace('/^##\s+(.+)$/m', '<h3>$1</h3>', $rendered);
            // Numbered section headers: 1. **Title**
            $rendered = preg_replace('/^(\d+)\.\s*<strong>(.+?)<\/strong>/m', '<h3>$1. $2</h3>', $rendered);
            // Bullet lists
            $rendered = preg_replace_callback('/(?:^- .+$\n?)+/m', static function (array $m): string {
                $items = preg_split('/\n/', trim($m[0]));
                $lis = '';
                foreach ($items as $item) {
                    $text = preg_replace('/^- /', '', $item);
                    if ($text !== '') $lis .= '<li>' . $text . '</li>';
                }
                return '<ul>' . $lis . '</ul>';
            }, $rendered);
            // Numbered lists (1. item, 2. item)
            $rendered = preg_replace_callback('/(?:^\d+\.\s+.+$\n?)+/m', static function (array $m): string {
                $items = preg_split('/\n/', trim($m[0]));
                $lis = '';
                foreach ($items as $item) {
                    $text = preg_replace('/^\d+\.\s+/', '', $item);
                    if ($text !== '') $lis .= '<li>' . $text . '</li>';
                }
                return '<ol>' . $lis . '</ol>';
            }, $rendered);
            // Paragraphs
            $rendered = preg_replace('/\n{2,}/', '</p><p>', $rendered);
            $rendered = str_replace("\n", '<br>', $rendered);
            echo '<p>' . $rendered . '</p>';
        ?>
    </div>
    <p class="mt-3 text-[10px] text-slate-500">Generated by <?= htmlspecialchars((string) ($aiSummary['model'] ?? ''), ENT_QUOTES) ?> at <?= htmlspecialchars((string) ($aiSummary['generated_at'] ?? ''), ENT_QUOTES) ?> · Locked <?= htmlspecialchars((string) ($theater['locked_at'] ?? ''), ENT_QUOTES) ?></p>
</section>
<?php elseif ($isLocked): ?>
<section class="surface-primary mt-4">
    <div class="flex items-center justify-between">
        <div class="flex items-center gap-3">
            <h2 class="text-lg font-semibold text-slate-50">AI Briefing</h2>
        </div>
        <span class="inline-flex items-center gap-1.5 rounded-full bg-slate-700 px-2.5 py-1 text-[10px] uppercase tracking-wider text-slate-300">
            <svg class="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
            Locked
        </span>
    </div>
    <?php if ($aarError !== null): ?>
        <p class="text-sm text-red-400 mt-2">AI generation failed at lock time: <?= htmlspecialchars($aarError, ENT_QUOTES) ?></p>
    <?php else: ?>
        <p class="text-sm text-muted mt-2">Report locked but no AI briefing was generated (AI may be disabled).</p>
    <?php endif; ?>
    <p class="mt-2 text-[10px] text-slate-500">Locked <?= htmlspecialchars((string) ($theater['locked_at'] ?? ''), ENT_QUOTES) ?></p>
</section>
<?php elseif (!$isLocked): ?>
<section class="surface-primary mt-4">
    <div class="flex items-center justify-between">
        <div>
            <h2 class="text-lg font-semibold text-slate-50">AI Briefing</h2>
            <p class="text-sm text-muted mt-1">Lock this battle report to generate a one-time AI briefing. Once locked, the report cannot be regenerated.</p>
        </div>
        <form method="POST" class="inline" onsubmit="return confirm('Lock this battle report and generate the AI briefing? This action cannot be undone.');">
            <input type="hidden" name="lock_report" value="1">
            <button type="submit" class="inline-flex items-center gap-2 rounded-lg bg-amber-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-amber-500 transition-colors" onclick="this.disabled=true;this.innerHTML='<svg class=\'animate-spin h-4 w-4\' viewBox=\'0 0 24 24\'><circle class=\'opacity-25\' cx=\'12\' cy=\'12\' r=\'10\' stroke=\'currentColor\' stroke-width=\'4\' fill=\'none\'></circle><path class=\'opacity-75\' fill=\'currentColor\' d=\'M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z\'></path></svg> Locking &amp; Generating…';this.form.submit();">
                <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
                Lock &amp; Generate AI Report
            </button>
        </form>
    </div>
</section>
<?php endif; ?>
