from __future__ import annotations

from typing import Any

# Active Python-native recurring jobs.
#
# Timing philosophy: run as close to real-time as possible without flooding
# ESI or the database.  ESI caches market data for ~5 minutes and structure
# data for ~60 seconds, so ESI-facing syncs respect those floors.  Compute
# and summary jobs are DB-only and can safely re-run every few minutes with
# minimal cooldown.  Lock groups serialise jobs that write to overlapping
# tables; unrelated jobs run in parallel.

WORKER_JOB_DEFINITIONS: dict[str, dict[str, Any]] = {
    # ── Graph pipeline (serialised via lock_group) ──────────────────────
    "compute_graph_sync":                       {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "lock_group": "graph_pipeline",       "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_graph_sync_doctrine_dependency":   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 600,   "max_staleness_seconds": 1800,  "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "lock_group": "graph_pipeline",       "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_graph_sync_battle_intelligence":   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 600,   "max_staleness_seconds": 1800,  "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "lock_group": "graph_pipeline",       "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_graph_derived_relationships":      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 600,   "max_staleness_seconds": 1800,  "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "lock_group": "graph_pipeline",       "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_graph_insights":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "lock_group": "graph_pipeline",       "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_graph_prune":                      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "min_interval_seconds": 900,   "max_staleness_seconds": 3600,  "cooldown_seconds": 30,  "runtime_class": "graph_heavy",  "resource_cost": "medium", "lock_group": "graph_pipeline",       "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_graph_topology_metrics":           {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 600,   "max_staleness_seconds": 1800,  "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "lock_group": "graph_pipeline",       "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4},

    # ── Battle intelligence (serialised via lock_group) ─────────────────
    "compute_battle_rollups":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 600,   "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "lock_group": "battle_intelligence",  "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_battle_target_metrics":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 600,   "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "lock_group": "battle_intelligence",  "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_battle_anomalies":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 600,   "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "lock_group": "battle_intelligence",  "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_battle_actor_features":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 600,   "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "lock_group": "battle_intelligence",  "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_suspicion_scores":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "lock_group": "battle_intelligence",  "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_suspicion_scores_v2":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "lock_group": "battle_intelligence",  "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_behavioral_baselines":             {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 600,   "max_staleness_seconds": 1800,  "cooldown_seconds": 15,  "runtime_class": "battle_heavy", "resource_cost": "high",   "lock_group": "battle_intelligence",  "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_counterintel_pipeline":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 600,   "max_staleness_seconds": 1800,  "cooldown_seconds": 15,  "runtime_class": "battle_heavy", "resource_cost": "high",   "lock_group": "battle_intelligence",  "opportunistic_background": False, "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 4},

    # ── Market intelligence (serialised via lock_group) ─────────────────
    "compute_buy_all":                          {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 10,  "runtime_class": "market_heavy", "resource_cost": "high",   "lock_group": "market_intelligence",  "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4},
    "compute_signals":                          {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 10,  "runtime_class": "market_heavy", "resource_cost": "medium", "lock_group": "market_intelligence",  "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4},

    # ── ESI-facing syncs (respect ESI cache timers) ─────────────────────
    "market_hub_current_sync":                  {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 600,   "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "market_sync",          "opportunistic_background": False, "timeout_seconds": 240,  "memory_limit_mb": 512,  "retry_delay_seconds": 15, "max_attempts": 4},
    "alliance_current_sync":                    {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 180,   "max_staleness_seconds": 600,   "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "market_sync",          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 512,  "retry_delay_seconds": 15, "max_attempts": 4},
    "current_state_refresh_sync":               {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "min_interval_seconds": 120,   "max_staleness_seconds": 600,   "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "lock_group": "status_refresh",       "opportunistic_background": False, "timeout_seconds": 120,  "memory_limit_mb": 384,  "retry_delay_seconds": 15, "max_attempts": 4},

    # ── Historical / backfill (relaxed, background) ─────────────────────
    "market_hub_historical_sync":               {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 21600, "max_staleness_seconds": 43200, "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "market_backfill",      "opportunistic_background": True,  "timeout_seconds": 3600, "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3},
    "alliance_historical_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 21600, "max_staleness_seconds": 43200, "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "market_backfill",      "opportunistic_background": True,  "timeout_seconds": 3600, "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3},

    # ── Analytics ────────────────────────────────────────────────────────
    "analytics_bucket_1h_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "min_interval_seconds": 600,   "max_staleness_seconds": 1800,  "cooldown_seconds": 10,  "runtime_class": "sync_light",   "resource_cost": "low",    "lock_group": "analytics",            "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4},
    "analytics_bucket_1d_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 3600,  "max_staleness_seconds": 21600, "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "low",    "lock_group": "analytics",            "opportunistic_background": True,  "timeout_seconds": 240,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4},

    # ── Summaries & intelligence ────────────────────────────────────────
    "activity_priority_summary_sync":           {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "lock_group": "summaries",            "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4},
    "dashboard_summary_sync":                   {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "lock_group": "summaries",            "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4},
    "loss_demand_summary_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "lock_group": "summaries",            "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4},
    "doctrine_intelligence_sync":               {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "intelligence",         "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 512,  "retry_delay_seconds": 30, "max_attempts": 4},
    "deal_alerts_sync":                         {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 180,   "max_staleness_seconds": 600,   "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "lock_group": "intelligence",         "opportunistic_background": False, "timeout_seconds": 90,   "memory_limit_mb": 384,  "retry_delay_seconds": 15, "max_attempts": 4},
    "rebuild_ai_briefings":                     {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 900,   "max_staleness_seconds": 2700,  "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "intelligence",         "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 4},
    "forecasting_ai_sync":                      {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 3600,  "max_staleness_seconds": 10800, "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "intelligence",         "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 4},
    "market_comparison_summary_sync":           {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "min_interval_seconds": 300,   "max_staleness_seconds": 900,   "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "market_intelligence",  "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 512,  "retry_delay_seconds": 30, "max_attempts": 4},
    "market_hub_local_history_sync":            {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 3600,  "max_staleness_seconds": 21600, "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "market_backfill",      "opportunistic_background": True,  "timeout_seconds": 1800, "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3},

    # ── Intelligence pipeline ──────────────────────────────────────────
    "esi_character_queue_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 1800,  "max_staleness_seconds": 7200,  "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "low",    "lock_group": "intelligence",         "opportunistic_background": True,  "timeout_seconds": 120,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4},
    "esi_alliance_history_sync":                {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 3600,  "max_staleness_seconds": 14400, "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "lock_group": "esi_history",          "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3},
    "intelligence_pipeline":                    {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "min_interval_seconds": 3600,  "max_staleness_seconds": 14400, "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "lock_group": "graph_pipeline",       "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3},
}

# Explicitly retired from recurring execution — no Python-native processor exists.
DISABLED_WORKER_JOBS: dict[str, str] = {}

RETIRED_PHP_SYNC_PATHS: dict[str, str] = {
    "bin/killmail_sync.php": "Replaced by python -m orchestrator zkill-worker stream worker.",
    "bin/precompute_buy_all.php": "Replaced by Python compute_buy_all worker processor.",
    "bin/sync_runner.php": "Retired legacy manual PHP sync multiplexer; queue-backed Python worker pool is authoritative.",
}
