# ── Job Wiring Checklist ─────────────────────────────────────────────────────
# New Python job?  See python/orchestrator/jobs/__init__.py for the full
# checklist (11 registration points).  In THIS file you need:
#   - Add entry to WORKER_JOB_DEFINITIONS with scheduling, deps, resources
# ─────────────────────────────────────────────────────────────────────────────
from __future__ import annotations

from typing import Any

# Active Python-native recurring jobs.
#
# Scheduling philosophy
# ─────────────────────
# Jobs declare explicit *dependencies* (``depends_on``) so the scheduler can
# build a DAG and dispatch independent work concurrently.  Within a dependency
# chain, upstream jobs finish before downstream ones start.
#
# ``concurrency_group`` replaces the old ``lock_group`` for *resource-level*
# mutual exclusion.  Two jobs in the same concurrency group will never overlap,
# regardless of dependencies — this protects shared physical resources (e.g.
# Neo4j write connections, heavy memory consumers).
#
# Jobs that share neither a dependency edge nor a concurrency group are free to
# run in parallel, allowing the scheduler to saturate available workers.
#
# Timing: Job intervals are controlled exclusively by sync_schedules in the
# database (interval_minutes / next_due_at).  No hardcoded intervals here.

WORKER_JOB_DEFINITIONS: dict[str, dict[str, Any]] = {

    # ── Graph pipeline ────────────────────────────────────────────────────
    # Concurrency strategy: only the root write-heavy sync uses the
    # ``graph_neo4j_write`` group to protect against concurrent bulk writes.
    # Downstream read/compute jobs use the DAG dependencies for ordering and
    # run without a concurrency group so they can be dispatched in parallel
    # once their upstream completes.
    #
    # Tier 0: root sync — builds the base knowledge graph (exclusive write)
    "compute_graph_sync":                       {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "graph_neo4j_write", "depends_on": [],                                                                       "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute-graph"},
    "graph_universe_sync":                      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "medium", "concurrency_group": "graph_neo4j_write", "depends_on": [],                                                                       "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-graph"},
    "compute_graph_sync_killmail_entities":     {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "graph_neo4j_write", "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-graph"},
    # Tier 1: these read from the base graph and can run in parallel
    "compute_graph_sync_doctrine_dependency":   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-graph"},
    "compute_graph_sync_battle_intelligence":   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-graph"},
    "compute_graph_derived_relationships":      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-graph"},
    "compute_graph_prune":                      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "graph_heavy",  "resource_cost": "medium", "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-graph"},
    "compute_graph_topology_metrics":           {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute-graph"},
    "graph_data_quality_check":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "graph_heavy",  "resource_cost": "medium", "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-graph"},
    "graph_temporal_metrics_sync":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-graph"},
    "graph_typed_interactions_sync":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-graph"},
    # Tier 2: depend on derived relationships — can run in parallel with each other
    "compute_graph_insights":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync", "compute_graph_derived_relationships"],             "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-graph", "empty_output_is_suspicious": True},
    "graph_community_detection_sync":           {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_derived_relationships"],                                  "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-graph"},
    "graph_motif_detection_sync":               {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_derived_relationships"],                                  "opportunistic_background": True,  "timeout_seconds": 3600, "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-graph"},
    "graph_evidence_paths_sync":                {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_derived_relationships"],                                  "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-graph"},
    "graph_query_plan_validation":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 300, "runtime_class": "graph_heavy",  "resource_cost": "low",    "concurrency_group": "",                  "depends_on": ["compute_graph_derived_relationships"],                                  "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 2, "lane": "compute-graph"},
    "neo4j_ml_exploration":                     {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_derived_relationships", "graph_community_detection_sync"], "opportunistic_background": True,  "timeout_seconds": 1800, "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-graph"},
    # Bloom operational intelligence — entry-point labels (cheap, small writes)
    "compute_bloom_entry_points":               {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "low",    "concurrency_group": "",                  "depends_on": ["compute_suspicion_scores_v2", "compute_graph_sync"],                     "opportunistic_background": True,  "timeout_seconds": 240,  "memory_limit_mb": 384,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-graph"},
    # Tier 3: intelligence pipeline reads from insights
    "intelligence_pipeline":                    {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_insights"],                                               "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-graph"},

    # ── Battle intelligence ───────────────────────────────────────────────
    # Concurrency strategy: only the root rollup job uses a concurrency
    # group to protect against overlapping heavy writes.  Downstream
    # read/compute jobs rely on DAG dependencies for ordering and can run
    # in parallel once their upstream completes.
    #
    # Tier 0: root rollups (exclusive write)
    "compute_battle_rollups":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "battle_rollup_write", "depends_on": [],                                                                      "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-battle", "empty_output_is_suspicious": True},
    # Tier 1: these three read from rollups and can run in parallel
    "compute_battle_target_metrics":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_rollups"],                                               "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-battle", "empty_output_is_suspicious": True},
    "compute_battle_anomalies":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_rollups"],                                               "opportunistic_background": False, "timeout_seconds": 1200, "memory_limit_mb": 4096, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-battle", "empty_output_is_suspicious": True},
    "compute_battle_actor_features":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_rollups"],                                               "opportunistic_background": False, "timeout_seconds": 1800, "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-battle", "empty_output_is_suspicious": True},
    # Tier 2: suspicion scores need target metrics + anomalies — can run in parallel
    "compute_suspicion_scores":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_target_metrics", "compute_battle_anomalies"],             "opportunistic_background": True,  "timeout_seconds": 1500, "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-battle"},
    "compute_suspicion_scores_v2":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_target_metrics", "compute_battle_anomalies", "compute_battle_actor_features"], "opportunistic_background": False, "timeout_seconds": 2400, "memory_limit_mb": 4096, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-battle", "empty_output_is_suspicious": True},
    "compute_behavioral_baselines":             {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 15,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_actor_features"],                                        "opportunistic_background": True,  "timeout_seconds": 1200, "memory_limit_mb": 5120, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-behavioral", "empty_output_is_suspicious": True},
    # Tier 3: cohort baselines need suspicion v2 + baselines + actor features
    "compute_cohort_baselines":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",                    "depends_on": ["compute_suspicion_scores_v2", "compute_behavioral_baselines"],           "opportunistic_background": True,  "timeout_seconds": 5400, "memory_limit_mb": 2048, "retry_delay_seconds": 300, "max_attempts": 2, "lane": "compute-behavioral"},
    # Tier 3: counterintel needs suspicion v2 + baselines
    "compute_counterintel_pipeline":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 15,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_suspicion_scores_v2", "compute_behavioral_baselines"],           "opportunistic_background": False, "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute-battle", "empty_output_is_suspicious": True},
    # Tier 4: spy detection platform (Phase 2 — feature & label foundation)
    "compute_spy_feature_snapshots":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",                    "depends_on": ["compute_counterintel_pipeline", "neo4j_ml_exploration", "graph_community_detection_sync", "compute_suspicion_scores_v2"], "opportunistic_background": True, "timeout_seconds": 600, "memory_limit_mb": 768, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-spy"},
    "build_spy_training_split":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 300, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",                    "depends_on": ["compute_spy_feature_snapshots"],                                         "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-spy"},
    # Tier 5: spy detection platform (Phase 3 — identity resolution)
    "compute_identity_resolution":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 300, "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_spy_feature_snapshots", "graph_community_detection_sync", "neo4j_ml_exploration", "compute_counterintel_pipeline"], "opportunistic_background": True, "timeout_seconds": 1200, "memory_limit_mb": 1536, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-spy"},
    # Tier 6: spy detection platform (Phase 4 — ring case detection)
    "graph_spy_ring_projection":                {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 300, "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_graph_derived_relationships", "graph_typed_interactions_sync", "compute_identity_resolution"], "opportunistic_background": True, "timeout_seconds": 1200, "memory_limit_mb": 1536, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-spy"},
    "compute_spy_network_cases":                {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",                    "depends_on": ["graph_spy_ring_projection", "compute_identity_resolution", "compute_counterintel_pipeline"], "opportunistic_background": True, "timeout_seconds": 900, "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-spy"},
    # Tier 7: spy detection platform (Phase 5 — character spy risk)
    "compute_spy_risk_profiles":                {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",                    "depends_on": ["compute_counterintel_pipeline", "neo4j_ml_exploration", "graph_community_detection_sync", "compute_identity_resolution", "compute_spy_network_cases"], "opportunistic_background": False, "timeout_seconds": 900, "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-spy"},

    # ── Market intelligence ───────────────────────────────────────────────
    # Auto doctrine detector + its chained buy-all; signals depends on fresh market data.
    "compute_auto_doctrines":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "market_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 7200, "memory_limit_mb": 2048, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-misc"},
    "compute_auto_buyall":                      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "market_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["market_hub_current_sync", "alliance_current_sync", "compute_auto_doctrines"], "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    # NOTE: compute_auto_doctrines moved to compute-misc (85min baseline) — cross-lane dep from buyall is best-effort.
    "compute_signals":                          {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "market_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["market_hub_current_sync"],                                                 "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime", "empty_output_is_suspicious": True},
    "compute_economic_warfare":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "market_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": ["compute_battle_rollups"],                                                  "opportunistic_background": True,  "timeout_seconds": 1800, "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 4, "lane": "compute-misc"},

    # ── ESI-facing syncs (no upstream deps — these are data sources) ──────
    # Managed by esi-continuous daemon — not scheduled via lane runner.
    "entity_metadata_resolve_sync":             {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "continuous"},
    "market_hub_current_sync":                  {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 240,  "memory_limit_mb": 512,  "retry_delay_seconds": 15, "max_attempts": 4, "lane": "realtime"},
    "alliance_current_sync":                    {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 512,  "retry_delay_seconds": 15, "max_attempts": 4, "lane": "realtime"},
    "current_state_refresh_sync":               {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 120,  "memory_limit_mb": 384,  "retry_delay_seconds": 15, "max_attempts": 4, "lane": "realtime"},

    # ── Corporation standings (ESI, requires OAuth, corp-member rate group) ─
    "corp_standings_sync":                      {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "ingestion"},

    # ── Historical / backfill (relaxed, background, independent) ──────────
    "market_hub_historical_sync":               {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "market_backfill","depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 3600, "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-misc"},
    "alliance_historical_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "market_backfill","depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 3600, "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-misc"},

    # ── Analytics (independent of each other, no upstream deps) ───────────
    "analytics_bucket_1h_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-misc"},
    "analytics_bucket_1d_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 1200, "memory_limit_mb": 1536, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute-misc"},

    # ── Summaries & intelligence ──────────────────────────────────────────
    # Summaries can run in parallel — they read from different source tables
    "activity_priority_summary_sync":           {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "dashboard_summary_sync":                   {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "loss_demand_summary_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "deal_alerts_sync":                         {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["market_hub_current_sync"],                                                 "opportunistic_background": False, "timeout_seconds": 90,   "memory_limit_mb": 384,  "retry_delay_seconds": 15, "max_attempts": 4, "lane": "realtime"},
    "rebuild_ai_briefings":                     {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute-misc"},
    "forecasting_ai_sync":                      {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute-misc"},
    "market_comparison_summary_sync":           {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["market_hub_current_sync", "alliance_current_sync"],                        "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 512,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "market_hub_local_history_sync":            {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "market_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 1800, "memory_limit_mb": 16384, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-misc"},

    # ── Intelligence pipeline ─────────────────────────────────────────────
    # Managed by esi-continuous daemon — not scheduled via lane runner.
    "esi_character_queue_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 120,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "continuous"},
    "esi_affiliation_sync":                     {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["esi_character_queue_sync"],                                                "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "continuous"},
    "esi_alliance_history_sync":                {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["esi_affiliation_sync"],                                                    "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "ingestion"},
    "character_killmail_sync":                  {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["esi_affiliation_sync"],                                                    "opportunistic_background": True,  "timeout_seconds": 1800, "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "ingestion"},
    # Managed by esi-continuous daemon — not scheduled via lane runner.
    # concurrency_group intentionally empty: this job runs in a separate
    # daemon process, so the lane runner's group serialisation cannot apply
    # across process boundaries.  Rate limiting is enforced per-call via
    # evewho_rate_limit_requests.  Keeping it in 'evewho_api' would make the
    # group span lanes ('continuous' + 'ingestion') and fail the lane audit.
    "evewho_enrichment_sync":                   {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 600,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 4, "evewho_rate_limit_requests": 5, "lane": "continuous"},
    "evewho_alliance_member_sync":              {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "evewho_api",     "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 3600, "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 4, "evewho_rate_limit_requests": 5, "lane": "ingestion"},
    "tracked_alliance_member_sync":             {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "evewho_api",     "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 3600, "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 4, "evewho_rate_limit_requests": 5, "lane": "ingestion"},
    "graph_analyst_recalibration":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 300, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 384,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "maintenance"},

    # ── Theater intelligence ──────────────────────────────────────────────
    # Tier 0: clustering is the root
    # NOTE: concurrency_group removed — DAG deps already enforce ordering
    # (analysis+suspicion depend on clustering).  The old theater_compute
    # group serialised all three jobs (1920s total) which exceeded every
    # tier timeout budget and blocked all downstream compute-battle work.
    "theater_clustering":                       {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",              "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-battle"},
    # Tier 1: analysis and suspicion can run in parallel after clustering
    "theater_analysis":                         {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",              "depends_on": ["theater_clustering"],                                                       "opportunistic_background": False, "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-battle"},
    "theater_suspicion":                        {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",              "depends_on": ["theater_clustering"],                                                       "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 4, "lane": "compute-battle"},
    # Tier 2: graph integration needs both analysis and base graph
    "theater_graph_integration":                {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",              "depends_on": ["theater_analysis", "compute_graph_sync"],                                   "opportunistic_background": True,  "timeout_seconds": 21600, "memory_limit_mb": 2048, "retry_delay_seconds": 300, "max_attempts": 2, "lane": "compute-battle"},

    # ── Character feature windows ──────────────────────────────────────────
    "compute_character_feature_windows":        {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "compute_graph_topology_metrics"],                 "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-behavioral"},

    # ── Character pipeline worker (queue-driven) ───────────────────────────
    # No upstream dependencies — stages self-gate on data availability.
    # Histogram stage runs if any events exist; counterintel stage runs if
    # eligible battles exist.  Blocking on battle_anomalies would prevent
    # histogram computation for killmail-only characters.
    "character_pipeline_worker":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate", "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": False, "timeout_seconds": 120,  "memory_limit_mb": 512,  "retry_delay_seconds": 15, "max_attempts": 5, "lane": "compute-behavioral"},

    # ── Generalized co-presence edges ──────────────────────────────────────
    "compute_copresence_edges":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "compute_character_feature_windows"],               "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-behavioral"},

    # ── Temporal behavior detection ───────────────────────────────────────
    "temporal_behavior_detection":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_character_feature_windows"],                                        "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-behavioral"},

    # ── Intelligence expansion ─────────────────────────────────────────
    "battle_type_classification":               {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["compute_battle_rollups"],                                                    "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-battle"},
    "escalation_detection":                     {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_battle_rollups"],                                                    "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-battle"},
    "shell_corp_detection":                     {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["evewho_alliance_member_sync", "tracked_alliance_member_sync"],               "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-behavioral"},
    "staging_system_detection":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "graph_universe_sync"],                             "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-behavioral"},
    "pre_op_join_detection":                    {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "esi_alliance_history_sync"],                       "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-behavioral"},

    # ── Jump bridge sync ──────────────────────────────────────────────
    "jump_bridge_sync":                         {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["graph_universe_sync"],                                                       "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-misc"},

    # ── Alliance intelligence (dossiers, relationships, threat corridors) ─
    # Tier 0: relationship graph from killmail co-occurrence (heavy scan)
    "compute_alliance_relationships":           {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-misc", "empty_output_is_suspicious": True},
    # Tier 1: dossiers read from relationships + battle data
    "compute_alliance_dossiers":                {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_alliance_relationships", "compute_battle_rollups"],                  "opportunistic_background": True,  "timeout_seconds": 2100, "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-misc"},
    # Tier 1: threat corridors read from battle data + graph universe
    "compute_threat_corridors":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "graph_universe_sync"],                             "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-misc"},
    # Map intelligence: precompute chokepoints, centrality, communities, edge risk for the map module
    "compute_map_intelligence":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",               "depends_on": ["graph_universe_sync", "compute_threat_corridors"],                           "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 2048, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-misc"},
    # Tier 2: opposition daily snapshots — reads from dossiers, relationships, killmails
    "compute_opposition_daily_snapshots":       {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_alliance_dossiers", "compute_alliance_relationships"],               "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-misc"},

    # ── Graph pipeline (killmail edges + audit) ──────────────────────────
    "compute_graph_sync_killmail_edges":        {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "graph_neo4j_write", "depends_on": ["compute_graph_sync_killmail_entities", "compute_graph_sync_battle_intelligence"], "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-graph"},
    "graph_model_audit":                        {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 300, "runtime_class": "graph_heavy",  "resource_cost": "low",    "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "maintenance"},

    # ── Killmail repair ──────────────────────────────────────────────────
    "killmail_zkb_repair":                      {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "continuous"},

    # ── Behavioral scoring (reads from battle rollups, independent) ─────
    "compute_behavioral_scoring":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": ["compute_battle_rollups"],                                                    "opportunistic_background": True,  "timeout_seconds": 1800, "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute-behavioral", "empty_output_is_suspicious": True},

    # ── Sovereignty monitoring (ESI-facing, no upstream deps) ─────────
    "sovereignty_campaigns_sync":              {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": False, "timeout_seconds": 120,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "sovereignty_structures_sync":             {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 180, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "sovereignty_map_sync":                    {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 1800,"runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 384,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-misc"},
    "compute_sovereignty_alerts":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 120, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["sovereignty_campaigns_sync", "sovereignty_structures_sync"],                  "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},

    # ── Character Intelligence Profiles (CIP) — fusion engine ───────────
    # Tier 0: seed signal definitions (no deps, idempotent)
    "seed_signal_definitions":                  {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": True,  "timeout_seconds": 60,   "memory_limit_mb": 256,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "maintenance"},
    # Tier 1: signal emitter reads from all upstream intelligence tables
    "cip_signal_emitter":                       {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,   "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_suspicion_scores_v2", "compute_behavioral_scoring", "temporal_behavior_detection", "compute_copresence_edges"], "opportunistic_background": True,  "timeout_seconds": 1500, "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-cip", "empty_output_is_suspicious": True},
    # Tier 2: fusion reads from signal table (populated by emitter)
    "cip_fusion":                               {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,   "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["cip_signal_emitter"],                                                        "opportunistic_background": True,  "timeout_seconds": 1200, "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-cip", "empty_output_is_suspicious": True},
    # Tier 3: event engine reads from fused profiles (populated by fusion)
    "cip_event_engine":                         {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,   "runtime_class": "battle_heavy", "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["cip_fusion", "cip_compound_evaluator"],                                                                "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-cip"},
    # Tier 4: event digest produces analyst summaries from event data
    "cip_event_digest":                         {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["cip_event_engine"],                                                          "opportunistic_background": True,  "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-cip"},
    # Phase 4: compound signal evaluator — runs after fusion, feeds into event engine
    "cip_compound_evaluator":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,   "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["cip_fusion"],                                                                "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-cip", "empty_output_is_suspicious": True},
    # Phase 5: calibration — self-leveling thresholds from population stats (runs before event engine)
    "cip_calibration":                          {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["cip_fusion"],                                                                "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-cip"},
    # Phase 4.5: compound analytics — daily metrics snapshots for validation
    "cip_compound_analytics":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["cip_compound_evaluator", "cip_event_engine"],                                "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute-cip"},

    # ── Spy detection platform — Phase 6 (shadow ML) ─────────────────────
    "train_spy_shadow_model":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": ["compute_spy_feature_snapshots", "build_spy_training_split"],                  "opportunistic_background": True,  "timeout_seconds": 3600, "memory_limit_mb": 4096, "retry_delay_seconds": 300, "max_attempts": 2, "lane": "compute-spy"},
    "score_spy_shadow_ml":                      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 300,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_spy_feature_snapshots"],                                              "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 2048, "retry_delay_seconds": 60,  "max_attempts": 3, "lane": "compute-spy"},

    # ── Maintenance (independent, no upstream deps) ──────────────────────
    "cache_expiry_cleanup_sync":                {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "maintenance"},
    "log_to_issues":                           {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "sync_light",  "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 120,  "memory_limit_mb": 256,  "retry_delay_seconds": 300, "max_attempts": 2, "lane": "maintenance"},
    "discord_webhook_filter":                  {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 300,  "runtime_class": "sync_light",  "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 120,  "memory_limit_mb": 256,  "retry_delay_seconds": 60,  "max_attempts": 3, "lane": "maintenance"},
}

# Explicitly retired from recurring execution — no Python-native processor exists.
DISABLED_WORKER_JOBS: dict[str, str] = {}

RETIRED_PHP_SYNC_PATHS: dict[str, str] = {
    "bin/killmail_sync.php": "Replaced by python -m orchestrator zkill-worker stream worker.",
    "bin/precompute_buy_all.php": "Replaced by Python compute_auto_buyall worker processor.",
    "bin/sync_runner.php": "Retired legacy manual PHP sync multiplexer; queue-backed Python worker pool is authoritative.",
}


def _minimum_cooldown_seconds(job_key: str, definition: dict[str, Any]) -> int:
    lane = str(definition.get("lane") or "").strip().lower()
    workload = str(definition.get("workload_class") or "").strip().lower()
    runtime = str(definition.get("runtime_class") or "").strip().lower()
    key = job_key.lower()

    # Heavy historical/backfill/member crawls should not churn.
    if "historical" in key or "backfill" in key or "alliance_member" in key:
        return 3600
    if lane == "maintenance":
        return 1800
    if lane in {"compute-cip", "compute-behavioral"}:
        return 600
    if lane in {"compute-graph", "compute-battle"} or runtime in {"graph_heavy", "battle_heavy"}:
        return 300
    if lane in {"realtime", "ingestion"} or workload == "sync":
        return 60
    return 60


def _apply_cooldown_floor() -> None:
    for job_key, definition in WORKER_JOB_DEFINITIONS.items():
        configured = int(definition.get("cooldown_seconds", 60))
        definition["cooldown_seconds"] = max(configured, _minimum_cooldown_seconds(job_key, definition))


_apply_cooldown_floor()
