from __future__ import annotations

from typing import Any

# Active Python-native recurring jobs.
#
# Scheduling philosophy
# ─────────────────────
# Jobs declare explicit *dependencies* (``depends_on``) so the scheduler can
# build a DAG and dispatch independent work concurrently.  Within a dependency
# chain, upstream jobs finish before downstream ones start.
#
# ``concurrency_group`` replaces the old ``lock_group`` for *resource-level*
# mutual exclusion.  Two jobs in the same concurrency group will never overlap,
# regardless of dependencies — this protects shared physical resources (e.g.
# Neo4j write connections, heavy memory consumers).
#
# Jobs that share neither a dependency edge nor a concurrency group are free to
# run in parallel, allowing the scheduler to saturate available workers.
#
# Timing: Job intervals are controlled exclusively by sync_schedules in the
# database (interval_minutes / next_due_at).  No hardcoded intervals here.

WORKER_JOB_DEFINITIONS: dict[str, dict[str, Any]] = {

    # ── Graph pipeline ────────────────────────────────────────────────────
    # Concurrency strategy: only the root write-heavy sync uses the
    # ``graph_neo4j_write`` group to protect against concurrent bulk writes.
    # Downstream read/compute jobs use the DAG dependencies for ordering and
    # run without a concurrency group so they can be dispatched in parallel
    # once their upstream completes.
    #
    # Tier 0: root sync — builds the base knowledge graph (exclusive write)
    "compute_graph_sync":                       {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "graph_neo4j_write", "depends_on": [],                                                                       "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute"},
    "graph_universe_sync":                      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "medium", "concurrency_group": "graph_neo4j_write", "depends_on": [],                                                                       "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    "compute_graph_sync_killmail_entities":     {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "graph_neo4j_write", "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    # Tier 1: these read from the base graph and can run in parallel
    "compute_graph_sync_doctrine_dependency":   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    "compute_graph_sync_battle_intelligence":   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    "compute_graph_derived_relationships":      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    "compute_graph_prune":                      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "graph_heavy",  "resource_cost": "medium", "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    "compute_graph_topology_metrics":           {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute"},
    "graph_data_quality_check":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "graph_heavy",  "resource_cost": "medium", "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    "graph_temporal_metrics_sync":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    "graph_typed_interactions_sync":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    # Tier 2: depend on derived relationships — can run in parallel with each other
    "compute_graph_insights":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_sync", "compute_graph_derived_relationships"],             "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    "graph_community_detection_sync":           {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_derived_relationships"],                                  "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    "graph_motif_detection_sync":               {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_derived_relationships"],                                  "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    "graph_evidence_paths_sync":                {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_derived_relationships"],                                  "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    # Tier 3: intelligence pipeline reads from insights
    "intelligence_pipeline":                    {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",                  "depends_on": ["compute_graph_insights"],                                               "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},

    # ── Battle intelligence ───────────────────────────────────────────────
    # Concurrency strategy: only the root rollup job uses a concurrency
    # group to protect against overlapping heavy writes.  Downstream
    # read/compute jobs rely on DAG dependencies for ordering and can run
    # in parallel once their upstream completes.
    #
    # Tier 0: root rollups (exclusive write)
    "compute_battle_rollups":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "battle_rollup_write", "depends_on": [],                                                                      "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    # Tier 1: these three read from rollups and can run in parallel
    "compute_battle_target_metrics":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_rollups"],                                               "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    "compute_battle_anomalies":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_rollups"],                                               "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    "compute_battle_actor_features":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_rollups"],                                               "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    # Tier 2: suspicion scores need target metrics + anomalies — can run in parallel
    "compute_suspicion_scores":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_target_metrics", "compute_battle_anomalies"],             "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    "compute_suspicion_scores_v2":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_target_metrics", "compute_battle_anomalies", "compute_battle_actor_features"], "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    "compute_behavioral_baselines":             {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 15,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_battle_actor_features"],                                        "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 1024, "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},
    # Tier 3: cohort baselines need suspicion v2 + baselines + actor features
    "compute_cohort_baselines":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",                    "depends_on": ["compute_suspicion_scores_v2", "compute_behavioral_baselines"],           "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute"},
    # Tier 3: counterintel needs suspicion v2 + baselines
    "compute_counterintel_pipeline":            {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 15,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",                    "depends_on": ["compute_suspicion_scores_v2", "compute_behavioral_baselines"],           "opportunistic_background": False, "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute"},

    # ── Market intelligence ───────────────────────────────────────────────
    # Auto doctrine detector + its chained buy-all; signals depends on fresh market data.
    "compute_auto_doctrines":                   {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "market_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "realtime"},
    "compute_auto_buyall":                      {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "market_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["market_hub_current_sync", "alliance_current_sync", "compute_auto_doctrines"], "opportunistic_background": False, "timeout_seconds": 420,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "compute_signals":                          {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "market_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["market_hub_current_sync"],                                                 "opportunistic_background": False, "timeout_seconds": 300,  "memory_limit_mb": 768,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "compute_economic_warfare":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "market_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": ["compute_battle_rollups"],                                                  "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 4, "lane": "compute"},

    # ── ESI-facing syncs (no upstream deps — these are data sources) ──────
    "entity_metadata_resolve_sync":             {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "ingestion"},
    "market_hub_current_sync":                  {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 240,  "memory_limit_mb": 512,  "retry_delay_seconds": 15, "max_attempts": 4, "lane": "realtime"},
    "alliance_current_sync":                    {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 512,  "retry_delay_seconds": 15, "max_attempts": 4, "lane": "realtime"},
    "current_state_refresh_sync":               {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 120,  "memory_limit_mb": 384,  "retry_delay_seconds": 15, "max_attempts": 4, "lane": "realtime"},

    # ── Corporation standings (ESI, requires OAuth, corp-member rate group) ─
    "corp_standings_sync":                      {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "ingestion"},

    # ── Historical / backfill (relaxed, background, independent) ──────────
    "market_hub_historical_sync":               {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "market_backfill","depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 3600, "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    "alliance_historical_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "market_backfill","depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 3600, "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},

    # ── Analytics (independent of each other, no upstream deps) ───────────
    "analytics_bucket_1h_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 10,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "analytics_bucket_1d_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 240,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "compute"},

    # ── Summaries & intelligence ──────────────────────────────────────────
    # Summaries can run in parallel — they read from different source tables
    "activity_priority_summary_sync":           {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "dashboard_summary_sync":                   {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "loss_demand_summary_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "deal_alerts_sync":                         {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["market_hub_current_sync"],                                                 "opportunistic_background": False, "timeout_seconds": 90,   "memory_limit_mb": 384,  "retry_delay_seconds": 15, "max_attempts": 4, "lane": "realtime"},
    "rebuild_ai_briefings":                     {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute"},
    "forecasting_ai_sync":                      {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 4, "lane": "compute"},
    "market_comparison_summary_sync":           {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 5,   "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["market_hub_current_sync", "alliance_current_sync"],                        "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 512,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "market_hub_local_history_sync":            {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 1800, "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},

    # ── Intelligence pipeline ─────────────────────────────────────────────
    "esi_character_queue_sync":                 {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 120,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "ingestion"},
    "esi_alliance_history_sync":                {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "ingestion"},
    "evewho_enrichment_sync":                   {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "evewho_api",     "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 600,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 4, "evewho_rate_limit_requests": 5, "lane": "ingestion"},
    "evewho_alliance_member_sync":              {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "evewho_api",     "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 3600, "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 4, "evewho_rate_limit_requests": 5, "lane": "ingestion"},
    "tracked_alliance_member_sync":             {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "medium", "concurrency_group": "evewho_api",     "depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 3600, "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 4, "evewho_rate_limit_requests": 5, "lane": "ingestion"},
    "graph_analyst_recalibration":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 300, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 384,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "maintenance"},

    # ── Theater intelligence ──────────────────────────────────────────────
    # Tier 0: clustering is the root
    "theater_clustering":                       {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "theater_compute","depends_on": [],                                                                          "opportunistic_background": False, "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    # Tier 1: analysis and suspicion can run in parallel after clustering
    "theater_analysis":                         {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "theater_compute","depends_on": ["theater_clustering"],                                                       "opportunistic_background": False, "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    "theater_suspicion":                        {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "theater_compute","depends_on": ["theater_clustering"],                                                       "opportunistic_background": True,  "timeout_seconds": 420,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 4, "lane": "compute"},
    # Tier 2: graph integration needs both analysis and base graph
    "theater_graph_integration":                {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",              "depends_on": ["theater_analysis", "compute_graph_sync"],                                   "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},

    # ── Character feature windows ──────────────────────────────────────────
    "compute_character_feature_windows":        {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "compute_graph_topology_metrics"],                 "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},

    # ── Generalized co-presence edges ──────────────────────────────────────
    "compute_copresence_edges":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "compute_character_feature_windows"],               "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},

    # ── Temporal behavior detection ───────────────────────────────────────
    "temporal_behavior_detection":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_character_feature_windows"],                                        "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},

    # ── Intelligence expansion ─────────────────────────────────────────
    "battle_type_classification":               {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,  "runtime_class": "battle_heavy", "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["compute_battle_rollups"],                                                    "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    "escalation_detection":                     {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_battle_rollups"],                                                    "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    "shell_corp_detection":                     {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["evewho_alliance_member_sync", "tracked_alliance_member_sync"],               "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    "staging_system_detection":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "graph_universe_sync"],                             "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    "pre_op_join_detection":                    {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "esi_alliance_history_sync"],                       "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},

    # ── Jump bridge sync ──────────────────────────────────────────────
    "jump_bridge_sync":                         {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["graph_universe_sync"],                                                       "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},

    # ── Alliance intelligence (dossiers, relationships, threat corridors) ─
    # Tier 0: relationship graph from killmail co-occurrence (heavy scan)
    "compute_alliance_relationships":           {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    # Tier 1: dossiers read from relationships + battle data
    "compute_alliance_dossiers":                {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_alliance_relationships", "compute_battle_rollups"],                  "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    # Tier 1: threat corridors read from battle data + graph universe
    "compute_threat_corridors":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_battle_rollups", "graph_universe_sync"],                             "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    # Map intelligence: precompute chokepoints, centrality, communities, edge risk for the map module
    "compute_map_intelligence":                 {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "",               "depends_on": ["graph_universe_sync", "compute_threat_corridors"],                           "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 2048, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},
    # Tier 2: opposition daily snapshots — reads from dossiers, relationships, killmails
    "compute_opposition_daily_snapshots":       {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_alliance_dossiers", "compute_alliance_relationships"],               "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},

    # ── Graph pipeline (killmail edges + audit) ──────────────────────────
    "compute_graph_sync_killmail_edges":        {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 10,  "runtime_class": "graph_heavy",  "resource_cost": "high",   "concurrency_group": "graph_neo4j_write", "depends_on": ["compute_graph_sync_killmail_entities", "compute_graph_sync_battle_intelligence"], "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 768,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    "graph_model_audit":                        {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 300, "runtime_class": "graph_heavy",  "resource_cost": "low",    "concurrency_group": "",                  "depends_on": ["compute_graph_sync"],                                                   "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "maintenance"},

    # ── Killmail repair ──────────────────────────────────────────────────
    "killmail_zkb_repair":                      {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 120, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": True,  "timeout_seconds": 600,  "memory_limit_mb": 512,  "retry_delay_seconds": 120, "max_attempts": 3, "lane": "maintenance"},

    # ── Behavioral scoring (reads from battle rollups, independent) ─────
    "compute_behavioral_scoring":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "battle_heavy", "resource_cost": "high",   "concurrency_group": "",               "depends_on": ["compute_battle_rollups"],                                                    "opportunistic_background": True,  "timeout_seconds": 1800, "memory_limit_mb": 1024, "retry_delay_seconds": 120, "max_attempts": 3, "lane": "compute"},

    # ── Sovereignty monitoring (ESI-facing, no upstream deps) ─────────
    "sovereignty_campaigns_sync":              {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": False, "timeout_seconds": 120,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "sovereignty_structures_sync":             {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "immediate",  "cooldown_seconds": 180, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},
    "sovereignty_map_sync":                    {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 1800,"runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 384,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    "compute_sovereignty_alerts":              {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "high",   "freshness_sensitivity": "immediate",  "cooldown_seconds": 120, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["sovereignty_campaigns_sync", "sovereignty_structures_sync"],                  "opportunistic_background": False, "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 30, "max_attempts": 4, "lane": "realtime"},

    # ── Character Intelligence Profiles (CIP) — fusion engine ───────────
    # Tier 0: seed signal definitions (no deps, idempotent)
    "seed_signal_definitions":                  {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 3600, "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                            "opportunistic_background": True,  "timeout_seconds": 60,   "memory_limit_mb": 256,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "maintenance"},
    # Tier 1: signal emitter reads from all upstream intelligence tables
    "cip_signal_emitter":                       {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,   "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["compute_suspicion_scores_v2", "compute_behavioral_scoring", "temporal_behavior_detection", "compute_copresence_edges"], "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    # Tier 2: fusion reads from signal table (populated by emitter)
    "cip_fusion":                               {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,   "runtime_class": "battle_heavy", "resource_cost": "medium", "concurrency_group": "",               "depends_on": ["cip_signal_emitter"],                                                        "opportunistic_background": True,  "timeout_seconds": 900,  "memory_limit_mb": 1024, "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},
    # Tier 3: event engine reads from fused profiles (populated by fusion)
    "cip_event_engine":                         {"workload_class": "compute", "execution_mode": "python", "queue_name": "compute", "priority": "normal", "freshness_sensitivity": "background", "cooldown_seconds": 30,   "runtime_class": "battle_heavy", "resource_cost": "low",    "concurrency_group": "",               "depends_on": ["cip_fusion"],                                                                "opportunistic_background": True,  "timeout_seconds": 300,  "memory_limit_mb": 512,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "compute"},

    # ── Maintenance (independent, no upstream deps) ──────────────────────
    "cache_expiry_cleanup_sync":                {"workload_class": "sync",    "execution_mode": "python", "queue_name": "sync",    "priority": "low",    "freshness_sensitivity": "background", "cooldown_seconds": 60,  "runtime_class": "sync_light",   "resource_cost": "low",    "concurrency_group": "",               "depends_on": [],                                                                          "opportunistic_background": True,  "timeout_seconds": 180,  "memory_limit_mb": 384,  "retry_delay_seconds": 60, "max_attempts": 3, "lane": "maintenance"},
}

# Explicitly retired from recurring execution — no Python-native processor exists.
DISABLED_WORKER_JOBS: dict[str, str] = {}

RETIRED_PHP_SYNC_PATHS: dict[str, str] = {
    "bin/killmail_sync.php": "Replaced by python -m orchestrator zkill-worker stream worker.",
    "bin/precompute_buy_all.php": "Replaced by Python compute_auto_buyall worker processor.",
    "bin/sync_runner.php": "Retired legacy manual PHP sync multiplexer; queue-backed Python worker pool is authoritative.",
}
